---
title: "R Notebook"
output: html_notebook
---



# General Setup
Setup chunk

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8)
knitr::opts_knit$set(root.dir = normalizePath(".."))
knitr::opts_knit$get("root.dir")
```

Setup reticulate

```{r}
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
py_available(initialize = FALSE)
use_python(Sys.which("python"))
py_config()
```

Load libraries

```{r}
library(Seurat)
library(ggplot2)
library(ggridges)
library(dplyr)
library(destiny)
library(fdrtool)
library(gam)
library(gamclass)
library(dtw)
library(data.table)
library(clusterProfiler)
library(ReactomePA)
```

Load data (from all cells)

```{r}
allcells_css = readRDS(file = "data/processed/allcells_css.RDS")
end_cells = readRDS(file = "results/zonation_cond/end_cells_zonation_rank.RDS")
hep_cells = readRDS(file = "results/zonation_cond/hep_cells_zonation_rank.RDS")
```

Find genes varying along the pseudotime

```{r}
# will only use variable genes
hvg = end_cells$healthy@assays$SCT@var.features

# Fit GAM for each gene using pseudotime as independent variable.
t = end_cells$healthy$zonation_pt
gene_fit_p = c()
gene_fit_vals = data.frame(row.names = 1:100)
for(i in 1:length(hvg)){
  g = hvg[i]
  z = end_cells$healthy@assays$SCT@data[g,]
  
  d = data.frame(z=z, t=t)
  tmp = suppressMessages(gam(z ~ ns(t, df = 3), data=d))
  
  # bins for model fitting
  bb = seq(min(t), max(t), length.out = 100)
  gene_fit_vals[,g] = suppressMessages(predict(tmp,
                                               newdata = data.frame(t = bb)))
  p = summary(tmp)$parametric.anova$`Pr(>F)`[1]
  gene_fit_p = c(gene_fit_p, p)
  names(gene_fit_p)[length(gene_fit_p)] = g
}

gene_fit_p = fdrtool::fdrtool(gene_fit_p, statistic="pvalue", plot=F, 
                              verbose=F, cutoff.method="pct0", pct0=0.9)$qval
```



```{r}
# the following doublet clusters are hard to confirm just by their markers, 
#but this might be because they have lower expression of the markers of one of the cell type components,
#or might have been identified as doublets following subclustering only
remcl = c("Kupffer-Endothelial interaction 2", "Hepatocyte-Myeloid interaction", 
          "Macrophage-T cell interaction 2", "Hepatocyte-T cell interaction", 
          "Hepatocyte-Endothelial interaction")

doublets = allcells_css[,allcells_css$allcells_major=="Doublets" & 
                          !(allcells_css$allcells_clusters %in% remcl)]
```

Get markers for basal populations

```{r}
mk = read.csv("results/integr_allcells/css_allPops_markers.csv", header = T, stringsAsFactors = F)
doub_mk = mk[grepl("interaction", mk$cluster),]
mk = mk[order(mk$avg_logFC, decreasing = T),]
mk = mk[mk$p_val_adj<=0.05 & mk$avg_logFC>0,]

mk_orig_list = list("Endothelial" = c(mk[mk$cluster=="LSEC pericentral","gene"][1:5],
                               mk[mk$cluster=="LSEC periportal","gene"][1:5]),
                    "Lymphoid" = c(mk[mk$cluster=="ab-T cells","gene"][1:5],
                                   mk[mk$cluster=="B cells","gene"][1:5]),
                    "Kupffer" = mk[mk$cluster=="Kupffer cells","gene"][1:10],
                    "T cell" = mk[mk$cluster=="ab-T cells","gene"][1:10],
                    "Macrophage" = mk[mk$cluster=="Macrophages","gene"][1:10])

doub_exp_mk = lapply(mk_orig_list, function(x) Matrix::colSums(doublets@assays$SCT@data[x,]))
isdoub = c()
for(i in 1:ncol(doublets)){
  ann = doublets$allcells_simp[i]
  cts = names(mk_orig_list)[sapply(names(mk_orig_list), function(x) grepl(x, ann))]
  isdoub = c(isdoub, doub_exp_mk[[cts[1]]][i]>=1 & doub_exp_mk[[cts[2]]][i]>=1)
}
table(doublets$allcells_simp, isdoub)
```

Checking doublets for cell type markers, based on % of exp within markers for those cell types

```{r}
mk = read.csv("results/integr_allcells/css_allPops_markers.csv", header = T, stringsAsFactors = F)
doub_mk = mk[grepl("interaction", mk$cluster),]
mk = mk[order(mk$avg_logFC, decreasing = T),]
mk = mk[mk$p_val_adj<=0.05 & mk$avg_logFC>0,]

mk_top_list = list("LSEC central" = mk[mk$cluster=="LSEC pericentral","gene"],
                    "LSEC portal" = mk[mk$cluster=="LSEC periportal","gene"],
                    "B cell" = mk[mk$cluster=="B cells","gene"],
                    "Kupffer" = mk[mk$cluster=="Kupffer cells","gene"],
                    "T cell" = mk[mk$cluster=="ab-T cells","gene"],
                    "Macrophage" = mk[mk$cluster=="Macrophages","gene"])
mk_topfilt_l = list()
for(n in names(mk_top_list)){
  mk_topfilt_l[[n]] = setdiff(mk_top_list[[n]], unlist(mk_top_list[names(mk_top_list)!=n]))[1:100]
}
# also get markers for groups of cells - they have to be unique for that group (shared and not in others)
mk_topfilt_l$Endothelial = intersect(mk_top_list$`LSEC central`, mk_top_list$`LSEC portal`)
mk_topfilt_l$Endothelial = mk_topfilt_l$Endothelial[!mk_topfilt_l$Endothelial %in% unlist(mk_top_list[3:6])][1:100]
mk_topfilt_l$Lymphoid = intersect(mk_top_list$`B cell`, mk_top_list$`T cell`)
mk_topfilt_l$Lymphoid = mk_topfilt_l$Lymphoid[!mk_topfilt_l$Lymphoid %in% unlist(mk_top_list[c(1,2,4,6)])][1:100]
mk_topfilt_l$Lymphoid  = mk_topfilt_l$Lymphoid[!is.na(mk_topfilt_l$Lymphoid)]
mk_topfilt_l$Myeloid = intersect(mk_top_list$Macrophage, mk_top_list$Kupffer)
mk_topfilt_l$Myeloid = mk_topfilt_l$Myeloid[!mk_topfilt_l$Myeloid %in% unlist(mk_top_list[c(1,2,4,6)])][1:100]
mk_topfilt_l$Myeloid  = mk_topfilt_l$Lymphoid[!is.na(mk_topfilt_l$Myeloid)]

doub_exp_mk = lapply(mk_topfilt_l, function(x) Matrix::colSums(doublets@assays$SCT@data[x,]))
cnts_ct = t(Reduce(rbind, doub_exp_mk))
colnames(cnts_ct) = names(doub_exp_mk)
cnts_ct = t(apply(cnts_ct, 1, function(x) x/sum(x)*100))

rem = apply(cnts_ct, 1, function(x) any(x>60) | (x[1]+x[2]+x[7])>60 | 
              (x[3]+x[5]+x[8])>60 | (x[4]+x[6]+x[9])>60)
table(doublets$allcells_simp, !rem)
table(doublets$allcells_simp[!rem], doublets$Condition[!rem])

cnts_ct = cbind(doublets$allcells_simp, data.frame(cnts_ct, stringsAsFactors = F))
rem = c()
end_cols = c(2,3,8)
mye_cols = c(5,7,10)
lym_cols = c(4,6,9)
for(i in 1:nrow(cnts_ct)){
  ct = strsplit(as.character(cnts_ct[i,1]), " ")[[1]][1]
  if(ct=="Macrophage-Endothelial"){
    cols = list("c1" = end_cols, "c2" = mye_cols, "o" = lym_cols)
  }
  if(ct=="Kupffer-Endothelial"){
    cols = list("c1" = end_cols, "c2" = mye_cols, "o" = lym_cols)
  }
  if(ct=="Lymphoid-Endothelial"){
    cols = list("c1" = end_cols, "c2" = lym_cols, "o" = mye_cols)
  }
  if(ct=="Macrophage-T cell"){
    cols = list("c1" = lym_cols, "c2" = mye_cols, "o" = end_cols)
  }
  rem = c(rem, (sum(cnts_ct[i,cols$c1])>66 | sum(cnts_ct[i,cols$c1])<33) & 
            (sum(cnts_ct[i,cols$c2])>66 | sum(cnts_ct[i,cols$c2])<33) |
            sum(cnts_ct[i,cols$o])>33)
}
table(doublets$allcells_simp, !rem)
table(doublets$allcells_simp[!rem], doublets$Condition[!rem])
```




```{r}
sig_genes = gene_fit_p[gene_fit_p<=0.05]
top_sig_genes = names(sig_genes[order(sig_genes, decreasing = F)][1:1000])
top_sig_genes = top_sig_genes[top_sig_genes %in% rownames(doublets)]

data_gam_h = cbind(data.frame("DC1" = end_cells$healthy$zonation_pt),
                   Matrix::t(end_cells$healthy@assays$SCT@data[top_sig_genes,]))

gam_healthy = gam::gam(DC1 ~ ., data = data_gam_h, family = mgcv::betar(link = "logit", eps = 0.00001))

hea_pred = predict(gam_healthy,
                   Matrix::t(end_cells$healthy@assays$SCT@data[top_sig_genes,]), type = "response")

dou_pred = predict(gam_healthy,
                   Matrix::t(doublets@assays$SCT@data[top_sig_genes,]), type = "response")
```



```{r}
doublets@meta.data$dou_pred = dou_pred

plot_df = doublets@meta.data
plot_df$Condition = factor(plot_df$Condition, levels = c("healthy", "embolised", "regenerating"))
plot_df = plot_df[grepl("Endothelial", plot_df$allcells_simp) & !rem,]

ggplot(plot_df, aes(x = dou_pred, colour = Condition))+
  facet_wrap(~allcells_simp)+
  scale_colour_manual(values = c("green", "red", "salmon"))+
  geom_density()+
  theme_bw()+
  theme(legend.position = "bottom")

# save doublets with pseudotime
saveRDS(doublets, file = "results/doublet_zon/doublets_srat.RDS")
```



```{r}
tab_dou_list = list()
wtest_l = list()
for(ct in unique(plot_df$allcells_simp)){
  subdf = plot_df[plot_df$allcells_simp==ct,]
  tab_dou_list[[ct]] = table(subdf$Donor, subdf$Condition)
  
  wtest_l[[paste0("all_", ct)]] = wilcox.test(subdf$dou_pred[subdf$Condition=="embolised"],
                                         subdf$dou_pred[subdf$Condition=="regenerating"])$p.value
  
  for(dd in unique(subdf$Donor)[grepl("DD", unique(subdf$Donor))]){
    subsubdf = subdf[subdf$Donor==dd,]
    if(length(subsubdf$dou_pred[subsubdf$Condition=="embolised"])==0 |
       length(subsubdf$dou_pred[subsubdf$Condition=="embolised"])==0){
      wtest_l[[paste0(dd, "_", ct)]] = 1
    } else{
    wtest_l[[paste0(dd, "_", ct)]] = wilcox.test(subsubdf$dou_pred[subsubdf$Condition=="embolised"],
                                            subsubdf$dou_pred[subsubdf$Condition=="regenerating"])$p.value
    }
  }
}

sigdf = unique(plot_df[,c("Donor", "allcells_simp")])
star = c()
for(i in 1:nrow(sigdf)){
  if(!grepl("HD", sigdf[i,1])){
    ct = sigdf[i,2]
    dd = sigdf[i,1]
    val = names(wtest_l)[grepl(dd, names(wtest_l)) & grepl(ct, names(wtest_l))]
    star = c(star, ifelse(wtest_l[[val]]<=0.05, "*", ""))
  } else{
    star = c(star, "")
  }
}
sigdf$star = star
sigdf$x = 0.5
sigdf$y = 2.5

dt = plot_df[,c("Donor", "allcells_simp", "Condition")]
counts_df = aggregate(seq(nrow(dt))~., data=dt, FUN=length)
colnames(counts_df)[4] = "cc"

ggplot()+
  facet_grid(allcells_simp~Donor, scales = "free_y")+
  geom_density(data = plot_df, mapping = aes(x = dou_pred, colour = Condition))+
  geom_text(data = sigdf, mapping = aes(x = x, y = y, label = star))+
  geom_text(data = counts_df[counts_df$Condition!="regenerating",], 
            mapping = aes(label = cc, colour = Condition), x = 0.5, y = 4)+
  geom_text(data = counts_df[counts_df$Condition=="regenerating",], 
            mapping = aes(label = cc, colour = Condition), x = 0.5, y = 3.25)+
  labs(caption = "* = Wilcox test p-value<=0.05")+
  scale_colour_manual(values = c("green", "red", "salmon"))+
  theme_bw()+
  theme(legend.position = "bottom")
```



```{r, fig.height=5}
divs_zon = cut(plot_df$dou_pred, 10)
levels(divs_zon) = paste0("Z", 1:10)
doubles_sub = doublets[,rownames(plot_df)]
doubles_sub@meta.data$divs_zon = divs_zon

cpdb_g = read.csv("/links/groups/treutlein/USERS/tomasgomes/gene_refs/human/CellPhoneDB/gene_input.csv", 
                  header = T, stringsAsFactors = F)[,c(3,2)]
cpdb_c = read.csv("/links/groups/treutlein/USERS/tomasgomes/gene_refs/human/CellPhoneDB/complex_input.csv", 
                  header = T, stringsAsFactors = F)[,1:5]
cpdb_i=read.csv("/links/groups/treutlein/USERS/tomasgomes/gene_refs/human/CellPhoneDB/interaction_input.csv",
                header = T, stringsAsFactors = F)[,1:3]

cpdb_c = data.frame("uniprot" = rep(cpdb_c$complex_name, 4),
                    "uniprot2" = c(cpdb_c$uniprot_1, cpdb_c$uniprot_2, cpdb_c$uniprot_3, cpdb_c$uniprot_4))
cpdb_c = cpdb_c[!is.na(cpdb_c$uniprot2) & cpdb_c$uniprot2!="",]
cpdb_c = merge(cpdb_c, cpdb_g, by = 2, all.x = T)

# get all interaction annotation
id_tab = rbind(cpdb_g, cpdb_c[,c(3,2)])
int_annot = merge(cpdb_i, id_tab, by.x = 2, by.y = 2)
int_annot = unique(merge(int_annot, id_tab, by.x = 3, by.y = 2)[,c(3,4,5)])
lr = c()
for(int in unique(int_annot$id_cp_interaction)){
  lr1 = paste0(unique(int_annot[int_annot$id_cp_interaction==int,2]), collapse = ",")
  lr2 = paste0(unique(int_annot[int_annot$id_cp_interaction==int,3]), collapse = ",")
  lr = c(lr, paste0(lr1, "_", lr2))
}
names(lr) = unique(int_annot$id_cp_interaction)

# get homotypic interactions to discard from analysis
reform_list = readRDS(file = "results/cell_comm/reform_list.RDS")
inter_cpdb = Reduce(rbind, reform_list[4:6])
inter_cpdb$ct1[grepl("LSEC_", inter_cpdb$ct1)] = "LSEC"
inter_cpdb$ct1[grepl("LSEC_", inter_cpdb$ct2)] = "LSEC"
inter_cpdb = unique(inter_cpdb[,1:3])
inter_cpdb = inter_cpdb[inter_cpdb$ct1 %in% c("Macrophages", "Kupffer cells", "T cells", "LSEC", "B cells") |
                          inter_cpdb$ct2 %in% c("Macrophages", "Kupffer cells", "T cells", "LSEC", "B cells"),]
int_homotypic = unique(inter_cpdb$id_cp_interaction[inter_cpdb$ct1==inter_cpdb$ct2])
length(int_homotypic)

int_exp_l = list()
for(int in unique(int_annot$id_cp_interaction)){
  lig = unique(int_annot$hgnc_symbol.x[int_annot$id_cp_interaction==int])
  if(all(lig %in% rownames(doubles_sub))){
    lig_exp = Matrix::colSums(matrix(doubles_sub@assays$SCT@data[lig,], 
                                     ncol = ncol(doubles_sub))>0)==length(lig)
  } else{
    lig_exp = rep(F, ncol(doubles_sub))
  }
  rec = unique(int_annot$hgnc_symbol.y[int_annot$id_cp_interaction==int])
  if(all(rec %in% rownames(doubles_sub))){
    rec_exp = Matrix::colSums(matrix(doubles_sub@assays$SCT@data[rec,], 
                                     ncol = ncol(doubles_sub))>0)==length(rec)
  } else{
    rec_exp = rep(F, ncol(doubles_sub))
  }
  
  res = lig_exp & rec_exp
  if(sum(res)>0){
    int_exp_l[[int]] = res
  }
}
int_exp_df = Reduce(rbind, int_exp_l)
rownames(int_exp_df) = names(int_exp_l)

# interactions have to be in at least 10 cells and not have been detected as homotypic
# no need to filter by donor since these interactions all appear present in various
int_exp_df_filt = int_exp_df[rowSums(int_exp_df)>=10 & 
                               !(rownames(int_exp_df) %in% int_homotypic),]


pvals_l = list()
dat = doubles_sub@meta.data[,c("Condition", "dou_pred")]
for(ct in unique(doubles_sub$allcells_simp)){
  pvals_l[[ct]] = list()
  for(int in rownames(int_exp_df_filt)){
    dat$hasInt = int_exp_df_filt[int,]*1
    
    sub_dat = dat[doubles_sub$allcells_simp==ct,]
    glm_fit = glm(hasInt~dou_pred*Condition, data = sub_dat, 
                  family = "binomial", control = list(maxit = 500))
    pvals_l[[ct]][[int]] = summary(aov(glm_fit))[[1]]$`Pr(>F)`[-4]
  }
  pvals_l[[ct]] = Reduce(rbind, pvals_l[[ct]])
  rownames(pvals_l[[ct]]) = rownames(int_exp_df_filt)
  pvals_l[[ct]] = apply(pvals_l[[ct]], 2, p.adjust, method = "fdr")
  pvals_l[[ct]] = merge(pvals_l[[ct]], data.frame(lr), by = 0)
  colnames(pvals_l[[ct]]) = c("int", "zonation", "condition", "both", "genes")
}

dt = doubles_sub@meta.data[,c("dou_pred","allcells_simp","Condition")]
dt$divs_zon = cut(dt$dou_pred, 10)
dt = dt[,2:4]
plt_l = list()
for(ct in names(pvals_l)){
  for(tt in c("zonation", "condition", "both")){
    intssig = pvals_l[[ct]]$int[pvals_l[[ct]][,tt]<=0.05]
    intssig = intssig[!is.na(intssig)]
    intsig_l = list()
    for(int in intssig){
      counts_df = aggregate(int_exp_df_filt[int,]~., data=dt, FUN=function(x) sum(x)/length(x), drop=F)
      colnames(counts_df)[4] = "prop"
      counts_df$Condition = factor(counts_df$Condition, levels = c("healthy", "embolised", "regenerating"))
      intsig_l[[int]] = counts_df[counts_df$allcells_simp==ct,]
    }
    int_percond = list()
    for(cond in c("healthy", "embolised", "regenerating")){
      subintsig_l = lapply(intsig_l, function(x) x[x$Condition==cond,3:4])
      subintsig_p = lapply(subintsig_l, function(x) x[order(x$divs_zon, decreasing = F),"prop"])
      subintsig_p = Reduce(rbind, subintsig_p)
      subintsig_p[is.na(subintsig_p)] = 0
      rownames(subintsig_p) = names(subintsig_p)
      int_percond[[cond]] = subintsig_p
    }
    int_percond = Reduce(cbind, int_percond)
    rownames(int_percond) = lr[names(intsig_l)]
    
    if(dim(int_percond)[1]>2){
      plt_l[[paste0(ct, ", ", tt)]] = pheatmap::pheatmap(int_percond, cluster_cols = F,
                         gaps_col = c(10,20), fontsize_row = 7,
                         clustering_method = "ward.D", main = paste0(ct, ", ", tt))
    }
  }
}

for(ct in names(pvals_l)){
  ct2 = gsub(" ", ".", ct)
  write.csv(pvals_l[[ct]], file = paste0("results/doublet_zon/", ct2, "_testing_interactions.csv"), 
            col.names = T, row.names = F, quote = F)
}

ccc = doubles_sub$allcells_simp=="Macrophage-Endothelial interaction" & doubles_sub$Condition=="healthy"
cor(doubles_sub$nCount_SCT[ccc], doubles_sub$dou_pred[ccc])
View(cor(t(int_exp_df_filt[,ccc]), doubles_sub$dou_pred[ccc], method = "sp"))




int = "CPI-SS00581282E"
counts_df = aggregate(int_exp_df_filt[int,]~., data=dt, FUN=function(x) sum(x)/length(x), drop=F)
colnames(counts_df)[4] = "prop"
counts_df$Condition = factor(counts_df$Condition, levels = c("healthy", "embolised", "regenerating"))
ggplot(counts_df[counts_df$allcells_simp=="Kupffer-Endothelial interaction",], 
       aes(x = divs_zon, y = prop))+
  facet_wrap(~Condition)+
  geom_point()+
  theme_bw()
```

Trying the same with counts per bin (testing not working)

```{r}
int_cnt_l = list()
for(int in unique(int_annot$id_cp_interaction)){
  lig = unique(int_annot$hgnc_symbol.x[int_annot$id_cp_interaction==int])
  if(all(lig %in% rownames(doubles_sub))){
    lig_cnt = Matrix::colSums(matrix(doubles_sub@assays$SCT@data[lig,], 
                                     ncol = ncol(doubles_sub)))
  } else{
    lig_cnt = rep(0, ncol(doubles_sub))
  }
  rec = unique(int_annot$hgnc_symbol.y[int_annot$id_cp_interaction==int])
  if(all(rec %in% rownames(doubles_sub))){
    rec_cnt = Matrix::colSums(matrix(doubles_sub@assays$SCT@data[rec,], 
                                     ncol = ncol(doubles_sub)))
  } else{
    rec_cnt = rep(0, ncol(doubles_sub))
  }
  
  res = lig_cnt + rec_cnt
  if(sum(lig_cnt)>0 & sum(rec_cnt)>0){
    int_cnt_l[[int]] = res
  }
}
int_cnt_df = Reduce(rbind, int_cnt_l)
rownames(int_cnt_df) = names(int_cnt_l)

dt = doubles_sub@meta.data[,c("dou_pred","allcells_simp","Condition")]
dt$divs_zon = cut(dt$dou_pred, 10)
dt = dt[,2:4]
tot_counts = aggregate(doubles_sub@meta.data$nCount_SCT~., data=dt, FUN=function(x) sum(x), drop=F)
intsig_l = list()

for(int in intssig){
  int_counts = aggregate(int_cnt_df[int,]~., data=dt, FUN=function(x) sum(x), drop=F)
  int_counts[,4] = int_counts[,4]/tot_counts[,4]*10000
  colnames(int_counts)[4] = "propcnt"
  int_counts$Condition = factor(counts_df$Condition, levels = c("healthy", "embolised", "regenerating"))
  int_counts$propcnt[is.na(int_counts$propcnt)] = 0
  intsig_l[[int]] = int_counts
}
pvals_cnt_l = list()
for(ct in unique(doubles_sub$allcells_simp)){
  pvals_cnt_l[[ct]] = list()
  for(int in names(intsig_l)){
    sub_dat = intsig_l[[int]][intsig_l[[int]]$allcells_simp==ct,]
    glm_fit = glm(propcnt~divs_zon*Condition, data = sub_dat, control = list(maxit = 500))
    if(!is.null(summary(aov(glm_fit))[[1]]$`Pr(>F)`[-4])){
      pvals_cnt_l[[ct]][[int]] = summary(aov(glm_fit))[[1]]$`Pr(>F)`[-4]
    }
  }
  if(length(pvals_cnt_l[[ct]])>0){
    pvals_cnt_l[[ct]] = Reduce(rbind, pvals_cnt_l[[ct]])
    rownames(pvals_cnt_l[[ct]]) = names(intsig_l)
    pvals_cnt_l[[ct]] = apply(pvals_cnt_l[[ct]], 2, p.adjust, method = "fdr")
    pvals_cnt_l[[ct]] = merge(pvals_cnt_l[[ct]], data.frame(lr), by = 0)
    colnames(pvals_cnt_l[[ct]]) = c("int", "zonation", "condition", "both", "genes")
  }
}





int_percond_cnt = list()
for(ct in unique(dt$allcells_simp)){
  int_percond = list()
  for(cond in c("healthy", "embolised", "regenerating")){
    subintsig_l = lapply(intsig_l, function(x) x[x$Condition==cond & x$allcells_simp==ct,3:4])
    subintsig_p = lapply(subintsig_l, function(x) x[order(x$divs_zon, decreasing = F),"propcnt"])
    subintsig_p = Reduce(rbind, subintsig_p)
    subintsig_p[is.na(subintsig_p)] = 0
    rownames(subintsig_p) = names(subintsig_p)
    int_percond[[cond]] = subintsig_p
  }
  int_percond = Reduce(cbind, int_percond)
  rownames(int_percond) = lr[names(intsig_l)]
  int_percond_cnt[[ct]] = int_percond
}


  pheatmap::pheatmap(int_percond, cluster_cols = F,
                     gaps_col = c(10,20), fontsize_row = 7,
                     clustering_method = "ward.D", main = paste0(ct, ", ", tt))
```





Markers for zonated doublets

```{r}
# markers per condition, zone by zone
de_zon_l = list()
for(ct in unique(doubles_sub$allcells_simp)){
  for(zz in unique(doubles_sub$divs_zon)){
    ids = paste0(ct, "_", zz)
    print(ids)
    subsrat = doubles_sub[,doubles_sub$allcells_simp==ct & doubles_sub$divs_zon==zz]
    subsrat = SetIdent(subsrat, value = "Condition")
    de_zon_l[[ids]] = FindAllMarkers(subsrat, logfc.threshold = 0.2, 
                                     pseudocount.use = 0.1, only.pos = F)
  }
}

# markers per condition
doubles_sub = SetIdent(doubles_sub, value = "Condition")
mkconddou = list()
for(ct in unique(doubles_sub$allcells_simp)){
  subsrat = doubles_sub[,doubles_sub$allcells_simp==ct]
  mkconddou[[ct]] = FindAllMarkers(subsrat, logfc.threshold = 0.2, pseudocount.use = 0.1,
                                   only.pos = F)
}
```



```{r}
subpops_dou = allcells_css[,allcells_css$allcells_simp %in% c("ab-T cells", "B cells", "Macrophages", 
                                                              "LSEC pericentral", "LSEC periportal", 
                                                              "Kupffer cells")]
subpops_doublets = merge(subpops_dou, doublets)

subpops_doublets = SetIdent(subpops_doublets, value = "allcells_simp")
allcomb = combn(unique(subpops_doublets@meta.data$allcells_simp), 2)
mk_1v1_list = list()
for(i in 1:ncol(allcomb)){
  cl1 = allcomb[1,i]
  cl2 = allcomb[2,i]
  mk_1v1_list[[paste0(cl1, "_", cl2)]] = FindMarkers(subpops_doublets, 
                                                     ident.1 = cl1, ident.2 = cl2)
}
saveRDS(mk_1v1_list, file = "results/doublet_zon/mk_1v1_list.RDS")

subpops_doublets@meta.data$allcells_gen = subpops_doublets@meta.data$allcells_simp
subpops_doublets@meta.data$allcells_gen[grepl("LSEC", subpops_doublets@meta.data$allcells_gen)] = "LSEC"
subpops_doublets@meta.data$allcells_gen[subpops_doublets@meta.data$allcells_gen %in% c("ab-T cells", 
                                                                             "B cells")] = "Lymphoid"

subpops_doublets = SetIdent(subpops_doublets, value = "allcells_gen")
allcomb = combn(unique(subpops_doublets@meta.data$allcells_gen), 2)
mk_1v1_gen_list = list()
for(i in 1:ncol(allcomb)){
  cl1 = allcomb[1,i]
  cl2 = allcomb[2,i]
  mk_1v1_gen_list[[paste0(cl1, "_", cl2)]] = FindMarkers(subpops_doublets, 
                                                         ident.1 = cl1, ident.2 = cl2)
}
saveRDS(mk_1v1_gen_list, file = "results/doublet_zon/mk_1v1_general_list.RDS")

subpops_doublets@meta.data$allcells_lym = subpops_doublets@meta.data$allcells_simp
subpops_doublets@meta.data$allcells_lym[grepl("LSEC", subpops_doublets@meta.data$allcells_lym) | 
                                          subpops_doublets@meta.data$allcells_lym %in% c("ab-T cells", 
                                                                             "B cells")] = "Lym-End"
subpops_doublets@meta.data$allcells_mac = subpops_doublets@meta.data$allcells_simp
subpops_doublets@meta.data$allcells_mac[grepl("LSEC", subpops_doublets@meta.data$allcells_mac) | 
                                          subpops_doublets@meta.data$allcells_mac=="Macrophages"] = "Mac-End"
subpops_doublets@meta.data$allcells_kup = subpops_doublets@meta.data$allcells_simp
subpops_doublets@meta.data$allcells_kup[grepl("LSEC", subpops_doublets@meta.data$allcells_kup) | 
                                          subpops_doublets@meta.data$allcells_kup=="Kupffer cells"]="Kup-End"

subpops_doublets = SetIdent(subpops_doublets, value = "allcells_lym")
mk_lym = FindMarkers(subpops_doublets, ident.1 = "Lym-End", ident.2 = "Lymphoid-Endothelial interaction")
subpops_doublets = SetIdent(subpops_doublets, value = "allcells_mac")
mk_mac = FindMarkers(subpops_doublets, ident.1 = "Mac-End", ident.2 = "Macrophage-Endothelial interaction")
subpops_doublets = SetIdent(subpops_doublets, value = "allcells_kup")
mk_kup = FindMarkers(subpops_doublets, ident.1 = "Kup-End", ident.2 = "Kupffer-Endothelial interaction")

mk_interact_all = list("mk_kup" = mk_kup, "mk_lym" = mk_lym, "mk_mac" = mk_mac)
saveRDS(mk_interact_all, file = "results/doublet_zon/mk_interact_all.RDS")
```




```{r}
for(n in names(mk_orig_list)){
  which.ct = grepl(n, doublets$allcells_simp)
  for(cc in unique(doublets$Condition)){
    doublets@assays$SCT@data[mk_orig_list[[n]],which.ct & doublets$Condition==cc]
  }
}
```




```{r}
cpdb_g = read.csv("/links/groups/treutlein/USERS/tomasgomes/gene_refs/human/CellPhoneDB/gene_input.csv", 
                  header = T, stringsAsFactors = F)[,c(3,2)]
cpdb_c = read.csv("/links/groups/treutlein/USERS/tomasgomes/gene_refs/human/CellPhoneDB/complex_input.csv", 
                  header = T, stringsAsFactors = F)[,1:5]
cpdb_i=read.csv("/links/groups/treutlein/USERS/tomasgomes/gene_refs/human/CellPhoneDB/interaction_input.csv",
                header = T, stringsAsFactors = F)[,1:3]

cpdb_c = data.frame("uniprot" = rep(cpdb_c$complex_name, 4),
                    "uniprot2" = c(cpdb_c$uniprot_1, cpdb_c$uniprot_2, cpdb_c$uniprot_3, cpdb_c$uniprot_4))
cpdb_c = cpdb_c[!is.na(cpdb_c$uniprot2) & cpdb_c$uniprot2!="",]
cpdb_c = merge(cpdb_c, cpdb_g, by = 2, all.x = T)

id_tab = rbind(cpdb_g, cpdb_c[,c(3,2)])
int_annot = merge(cpdb_i, id_tab, by.x = 2, by.y = 2)
int_annot = unique(merge(int_annot, id_tab, by.x = 3, by.y = 2)[,c(3,4,5)])

for(dou in unique(doublets$allcells_simp)){
  which.dou = doublets$allcells_simp==dou
  m1 = c()
  m2 = c()
  p1 = c()
  p2 = c()
  for(i in 1:nrow(int_annot)){
    if(int_annot[i,2] %in% rownames(doublets)){
      exp = as.vector(doublets[int_annot[i,2],which.dou]@assays$SCT@data)
      m1 = c(m1, mean(exp))
      p1 = c(p1, sum(exp>0)/sum(which.dou))
    } else{
      m1 = c(m1, 0)
      p1 = c(p1, 0)
    }
    if(int_annot[i,3] %in% rownames(doublets)){
      exp = as.vector(doublets[int_annot[i,3],which.dou]@assays$SCT@data)
      m2 = c(m2, mean(exp))
      p2 = c(p2, sum(exp>0)/sum(which.dou))
    } else{
      m2 = c(m2, 0)
      p2 = c(p2, 0)
    }
  }
  int_annot[,paste0("mean1_",dou)] = m1
  int_annot[,paste0("perc1_",dou)] = p1
  int_annot[,paste0("mean2_",dou)] = m2
  int_annot[,paste0("perc2_",dou)] = p2
}
```


```{r}
reform_list = readRDS(file = "results/cell_comm/reform_list.RDS")
```











```{r}
cor_doub = t(cor(dou_pred, as.matrix(Matrix::t(doublets@assays$SCT@data)),
              method = "sp"))

plot_df = cbind(doublets@meta.data, dou_pred)
cor_dou_list = list()
for(n in unique(plot_df$allcells_simp)){
  print(n)
  cells = plot_df$allcells_simp==n
  cor_dou_list[[n]] = t(cor(dou_pred[cells], as.matrix(Matrix::t(doublets@assays$SCT@data[,cells])),
                            method = "sp"))
}

cor_dou_c_list = list()
for(cc in unique(plot_df$Condition)){
  for(n in unique(plot_df$allcells_simp)){
    print(n)
    cells = plot_df$allcells_simp==n & plot_df$Condition==cc
    cor_dou_c_list[[paste0(cc, "_", n)]] = t(cor(dou_pred[cells],
                                                 as.matrix(Matrix::t(doublets@assays$SCT@data[,cells])),
                                                 method = "sp"))
  }
}
```




