---
title: "Hepatocyte population analysis"
output: html_notebook
---



# General Setup
Setup chunk

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8)
knitr::opts_knit$set(root.dir = normalizePath(".."))
knitr::opts_knit$get("root.dir")
```

Setup reticulate

```{r}
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
py_available(initialize = FALSE)
use_python(Sys.which("python"))
py_config()
```

Load libraries

```{r}
library(Seurat)
library(ggplot2)
library(destiny)
library(plyr)
library(dplyr)
library(RColorBrewer)
```

Load data (from all cells)

```{r}
allcells_css = readRDS(file = "data/processed/allcells_css.RDS")
```



# Immune Hepatocytes
Subset Hepatocytes

```{r}
hep_pops = unique(allcells_css$allcells_clusters)[grepl("Hepatocytes ",
                                                        unique(allcells_css$allcells_clusters))]
all_hep_cells = allcells_css[,allcells_css@meta.data$allcells_clusters %in% hep_pops]
all_hep_cells = suppressWarnings(SCTransform(all_hep_cells, do.correct.umi = T, verbose = F, 
                                             vars.to.regress=c("unique_name","nCount_RNA"),
                                             variable.features.rv.th = 1, seed.use = 1,
                                             return.only.var.genes = F, 
                                             variable.features.n = NULL))
all_hep_cells = RunPCA(all_hep_cells, verbose = F)
```

Choose dimensionality reduction

```{r, fig.height=8, fig.width=16}
pcadonorplt = list()
for(i in 1:15){
  n = 2*i
  pcadonorplt[[i]] = DimPlot(all_hep_cells, dims = (n-1):n, 
                             reduction = "pca", group.by = "Donor")+
    theme(aspect.ratio = 1, legend.position = "none")
}
cowplot::plot_grid(plotlist = pcadonorplt, ncol = 5, align = "hv")

ldims = list(1:30, c(1:2,4:30), c(1:2,4:20), c(1:2,4:16), c(2,4:16, 18, 20, 24:26))
for(i in 1:length(ldims)){
  all_hep_cells = RunUMAP(all_hep_cells, dims = ldims[[i]], verbose = F)
  plt1 = DimPlot(all_hep_cells, reduction = "umap", group.by = "Condition")
  plt2 = DimPlot(all_hep_cells, reduction = "umap", group.by = "Donor")
  print(plt1+plt2)
}

all_hep_cells = RunUMAP(all_hep_cells, dims = c(2,4:16, 18, 20, 24:26), verbose = F)
DimPlot(all_hep_cells, reduction = "umap", group.by = "Condition")
DimPlot(all_hep_cells, reduction = "umap", group.by = "Donor")
DimPlot(all_hep_cells, reduction = "umap", group.by = "Phase")
FeaturePlot(all_hep_cells, reduction = "umap", ncol = 4,
            features = c("ALB", "SAA1", "SAA2", "HAMP", "CYP1A2", "CYP2E1", "NNMT", "MT1G"))
```

Cluster and get markers

```{r}
all_hep_cells = FindNeighbors(all_hep_cells, reduction = "pca", dims = c(2,4:16, 18, 20, 24:26),
                            prune.SNN = 1/5, force.recalc = T, graph.name = "pca20")
all_hep_cells = FindClusters(all_hep_cells, algorithm = 2, verbose = F, 
                             graph.name = "pca20", resolution = seq(0.1, 1.1, 0.1))
DimPlot(all_hep_cells, reduction = "umap", group.by = "pca20_res.0.8", label = T)
DimPlot(all_hep_cells, reduction = "umap", group.by = "pca20_res.0.3", label = T)
DimPlot(all_hep_cells, reduction = "umap", group.by = "Donor", label = F)
DimPlot(all_hep_cells, reduction = "umap", group.by = "Condition", label = F)

all_hep_cells = SetIdent(all_hep_cells, value = "pca20_res.0.8")
mk_hepcells = FindAllMarkers(all_hep_cells, logfc.threshold = 0.2, pseudocount.use = 0.1)
write.csv(mk_hepcells[mk_hepcells$p_val_adj<=0.05,], 
          file = "results/hepatocytes/markers_hepatocytes_subpop_08.csv", row.names = T, quote = F)
saveRDS(mk_hepcells, file = "./results/hepatocytes/markers_hepatocytes_subpop_08.RDS")

all_hep_cells = SetIdent(all_hep_cells, value = "pca20_res.0.3")
mk_hepcells = FindAllMarkers(all_hep_cells, logfc.threshold = 0.2, pseudocount.use = 0.1)
write.csv(mk_hepcells[mk_hepcells$p_val_adj<=0.05,], 
          file = "results/hepatocytes/markers_hepatocytes_subpop_03.csv", row.names = T, quote = F)
saveRDS(mk_hepcells, file = "./results/hepatocytes/markers_hepatocytes_subpop_03.RDS")

#mk02 = FindMarkers(all_hep_cells, ident.1 = "0", ident.2 = "2", 
#                   logfc.threshold = 0.2, pseudocount.use = 0.1)
```

Save data

```{r}
saveRDS(all_hep_cells, file = "results/hepatocytes/all_hep_cells.RDS")
```



```{r}
annot_fine = list("10" = "Hepatic cancer/regeneration response", # https://journals.sagepub.com/doi/pdf/10.1177/153537020623100203, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2292801/, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4656314/, https://onlinelibrary.wiley.com/doi/full/10.1002/cbf.3288
                  "12" = "Dividing cells",
                  "11" = "Hepatocyte-Immune interaction",
                  "7" = "Periportal inflammation-inducing", # https://www.sciencedirect.com/science/article/pii/S0753332220308738, 
                  "0" = "Hepatocytes (HAMP+)",
                  "1" = "Pericentral Hepatocytes",
                  "8" = "Pericentral regenerating", # https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5349637/
                  "3" = "Fibrotic and regenerating response", # https://pubmed.ncbi.nlm.nih.gov/23770341/, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5937820/
                  "5" = "Unknown 1", # https://onlinelibrary.wiley.com/doi/full/10.1002/cbf.3288
                  "2" = "Ribosomal",
                  "4" = "Unknown 2"
                  )
```




```{r}
round(t(t(table(all_hep_cells$pca20_res.0.8, all_hep_cells$Condition))/colSums(table(all_hep_cells$pca20_res.0.8, all_hep_cells$Condition)))*100, 2)

round(t(t(table(all_hep_cells$pca20_res.0.3, all_hep_cells$Condition))/colSums(table(all_hep_cells$pca20_res.0.3, all_hep_cells$Condition)))*100, 2)

round(t(t(table(all_hep_cells$pca20_res.0.3, all_hep_cells$Donor))/colSums(table(all_hep_cells$pca20_res.0.3, all_hep_cells$Donor)))*100, 2)

pheatmap::pheatmap(round(t(t(table(all_hep_cells$pca20_res.0.8, all_hep_cells$Condition))/colSums(table(all_hep_cells$pca20_res.0.8, all_hep_cells$Condition)))*100, 2))
pheatmap::pheatmap(round(t(t(table(all_hep_cells$pca20_res.0.3, all_hep_cells$Condition))/colSums(table(all_hep_cells$pca20_res.0.3, all_hep_cells$Condition)))*100, 2))
```

