---
title: "R Notebook"
output: html_notebook
---



# General Setup
Setup chunk

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8)
knitr::opts_knit$set(root.dir = normalizePath(".."))
knitr::opts_knit$get("root.dir")
```

Setup reticulate

```{r}
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
py_available(initialize = FALSE)
use_python(Sys.which("python"))
py_config()
```

Load libraries

```{r}
library(Seurat)
library(ggplot2)
library(ggridges)
library(dplyr)
library(destiny)
library(fdrtool)
library(gam)
library(gamclass)
```




```{r}
allcells_css = readRDS(file = "data/processed/allcells_css_reannot.RDS")
hep_cells = readRDS(file = "results/zonation_cond/hep_cells_zonation_rank.RDS")
```

```{r}
hep = unlist(lapply(hep_cells, colnames))
hep_chl = allcells_css[,allcells_css$major_ct=="Cholangiocytes" | colnames(allcells_css) %in% hep]

hep_chl = suppressWarnings(SCTransform(hep_chl, do.correct.umi = T, verbose = F,
                                       vars.to.regress = c("unique_name","nCount_RNA"),
                                       variable.features.rv.th = 1, seed.use = 1,
                                       return.only.var.genes = F, variable.features.n = NULL))
hep_chl = RunPCA(hep_chl, verbose = F)
hep_chl = RunUMAP(hep_chl, dims = 1:15, verbose = F)

hep_chl = FindNeighbors(hep_chl, reduction = "pca", dims = 1:15,
                        force.recalc = T, graph.name = "hepchl_pca")
hep_chl = FindClusters(hep_chl, graph.name = "hepchl_pca", resolution = seq(0.2,1,0.1), 
                       verbose = F)
hep_chl = FindNeighbors(hep_chl, reduction = "css", force.recalc = T, graph.name = "hepchl_css")
hep_chl = FindClusters(hep_chl, graph.name = "hepchl_css", resolution = seq(0.2,1,0.1), 
                       verbose = F)
hep_chl = SetIdent(hep_chl, value = "hepchl_pca_res.1")
mk_hepchl = FindAllMarkers(hep_chl, logfc.threshold = 0.2, pseudocount.use = 0.1)

DimPlot(hep_chl, reduction = "umap", group.by = "hepchl_pca_res.1", label = T)
```

Save data

```{r}
saveRDS(hep_chl, file = "results/hep_chl.RDS")
saveRDS(mk_hepchl, file = "results/hep_chl_mks.RDS")
```

Obtain Diffusion maps projection

```{r}
sub_hep_chl = hep_chl[,hep_chl$hepchl_pca_res.1 %in% c(17,9,7)]
#sub_hep_chl = hep_chl[,hep_chl$cell_type=="Cholangiocytes"]

sub_hep_chl = suppressWarnings(SCTransform(sub_hep_chl, do.correct.umi = T, verbose = F,
                                           vars.to.regress = c("unique_name","nCount_RNA"),
                                           variable.features.rv.th = 1, seed.use = 1,
                                           return.only.var.genes = F, variable.features.n = NULL))
sub_hep_chl = RunPCA(sub_hep_chl, verbose = F)
sub_hep_chl = RunUMAP(sub_hep_chl, dims = 1:15, verbose = F)

sub_hep_chl = FindNeighbors(sub_hep_chl, reduction = "pca", dims = 1:15,
                            force.recalc = T, graph.name = "sub_pca")
sub_hep_chl = FindClusters(sub_hep_chl, graph.name = "sub_pca", 
                           resolution = seq(0.2,1,0.1), verbose = F)
DimPlot(sub_hep_chl, reduction = "umap", group.by = "hepchl_pca_res.1", label = T)
sub_hep_chl = SetIdent(sub_hep_chl, value = "sub_pca_res.0.2")
mk_subhepchl = FindAllMarkers(sub_hep_chl, logfc.threshold = 0.2, pseudocount.use = 0.1)

set.seed(1)
dm = DiffusionMap(sub_hep_chl@reductions$pca@cell.embeddings[,1:8], 
                  rotate = T, n_eigs = 3)
#dpt = DPT(dm, tips = c(7784, 8129, 1376))
dpt = DPT(dm)
plot(dpt)

xxx = data.frame(ct = sub_hep_chl$major_ct, dd = sub_hep_chl$Donor, cl = sub_hep_chl$hepchl_pca_res.1, 
                 cc = sub_hep_chl$Condition, g = sub_hep_chl@assays$SCT@data["CYP1A2",])
xxx = cbind(xxx, sub_hep_chl@reductions$umap@cell.embeddings)
xxx = cbind(xxx, dm@eigenvectors)
xxx$ind = 1:nrow(xxx)
dpt_flat <- branch_divide(dpt, integer(0L))
root = min(dpt_flat@branch[, 1], na.rm = TRUE)
dpt_vals = destiny:::dpt_for_branch(dpt_flat, root)
xxx$DPT = dpt_vals
#xxx$DPT = dpt$DPT10365
ggplot(xxx, aes(x = DC1, y = DC2, colour = cc))+geom_point()
ggplot(xxx, aes(x = DC1, y = DC2, colour = DPT))+geom_point()
ggplot(xxx[order(xxx$cl,decreasing = T),], aes(x = DC1, y = DC2, colour = cl))+geom_point()
ggplot(xxx, aes(x = DC1, y = DC2, colour = ct))+geom_point()
ggplot(xxx, aes(x = rank(DPT), colour = cl))+geom_density()
ggplot(xxx, aes(x = rank(DPT), colour = cc))+geom_density()
ggplot(xxx, aes(x = rank(DPT), colour = ct))+geom_density()
#corx = cor(as.matrix(Matrix::t(sub_hep_chl@assays$SCT@data)), rank(xxx$DPT), method = "sp")
```

Find varying genes - normalised by bins along the ranked pseudotime

```{r}
# get HVG from all conditions
hvg = rownames(sub_hep_chl@assays$SCT@data)

set.seed(1)
# filtering the cells by bins
bins = cut(rank(xxx$DPT), 100)
dons = xxx$dd
ndons = rowSums(table(bins, dons)>1)
ncells = rowSums(table(bins, dons))
sampleif = function(cells, bins, dons){
  res = c()
  for(d in unique(dons)){
    for(b in unique(bins)){
      x = cells[bins==b & dons==d]
      if(length(x)>=30){
        res = c(res, sample(x, 30, replace = F))
      } else if(length(x)>=1 & ndons[b]>=2 & ncells[b]>=10){
        res = c(res, x)
      } else{
        res = c(res, NULL)
      }
    }
  }
  return(res)
}
whichcells = sampleif(1:length(bins), bins, dons)

# Fit GAM for each gene using pseudotime as independent variable.
t = rank(xxx$DPT)
gene_fit_p = c()
gene_fit_vals = data.frame(row.names = 1:100)
for(i in 1:length(hvg)){
  g = hvg[i]
  z = sub_hep_chl@assays$SCT@data[g,]
  
  d = data.frame(z=z, t=t)
  tmp = suppressMessages(gam(z ~ ns(t, df = 3), data=d))
  
  # bins for model fitting
  bb = seq(min(t), max(t), length.out = 100)
  gene_fit_vals[,g] = suppressMessages(predict(tmp, newdata = data.frame(t = bb)))
  p = summary(tmp)$parametric.anova$`Pr(>F)`[1]
  gene_fit_p = c(gene_fit_p, p)
  names(gene_fit_p)[length(gene_fit_p)] = g
}

if(sum(is.na(gene_fit_p))>0){
  gene_fit_p[is.na(gene_fit_p)] = 1
}
gene_fit_p = fdrtool::fdrtool(gene_fit_p, statistic="pvalue", plot=F, 
                              verbose=F, cutoff.method="pct0", pct0=0.9)$qval

qvals_hc_list = gene_fit_p
fits_hc_list = gene_fit_vals
```

Save trajectories and genes

```{r}
#save(fits_hc_list, qvals_hc_list, 
#     file = "results/hep_hc_traj_qval_fits_rank.RData")
```







